"""empty message

Revision ID: 34c66d2f1f8e
Revises: 02aa01cb6db8
Create Date: 2024-06-14 19:22:30.498396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34c66d2f1f8e"
down_revision: Union[str, None] = "02aa01cb6db8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("refresh_token", sa.Uuid(), nullable=True))
    op.add_column("users", sa.Column("expired_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "expired_at")
    op.drop_column("users", "refresh_token")
    # ### end Alembic commands ###
