services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
        SENDGRID_API_KEY: ${SENDGRID_API_KEY}
        ACCOUNT_SID: ${ACCOUNT_SID}
        AUTH_TOKEN: ${AUTH_TOKEN}
        SENDER_PHONE: ${SENDER_PHONE}
        SENDER_EMAIL: ${SENDER_EMAIL}
        POSTGRES_URI: ${POSTGRES_URI}
        PAPERTRAIL_HOST: ${PAPERTRAIL_HOST}
        PAPERTRAIL_PORT: ${PAPERTRAIL_PORT}
        DOMAIN: ${DOMAIN}
        PRIVATE_KEY: ${PRIVATE_KEY}
        PUBLIC_KEY: ${PUBLIC_KEY}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: