name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ruff formatter
        uses: chartboost/ruff-action@v1
        with:
          args: format

      - name: ruff linter
        uses: chartboost/ruff-action@v1
        with:
          args: check --fix

