name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ruff format
        uses: chartboost/ruff-action@v1
        with:
          version: latest
          args: format
          src: "."

      - name: Run ruff check --fix
        uses: chartboost/ruff-action@v1
        with:
          version: latest
          args: check --fix
          src: "."

